apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: weather-app-argocd
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: https://github.com/mrd2k69/argocd-repo.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: weather-app
    
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
